const fs=require('node:fs'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const server=http.createServer((req,res)=>{const file=['/media-export.js','/motion-curve.js'].includes(req.url)?req.url.slice(1):'index.html';res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':'text/html; charset=utf-8');res.end(fs.readFileSync(file));}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));let browser;
 try{
  browser=await chromium.launch({headless:true,channel:process.env.TEST_BROWSER||undefined});const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:')?r.continue():r.abort());
  await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>typeof world!=='undefined'&&world);await page.evaluate(()=>{cancelAnimationFrame(rafId);window._dismissIntro?.();togglePanel();});
  const base=await page.evaluate(()=>JSON.stringify(PARAMS));await page.locator('#recordModeBtn').click();await page.locator('[data-record-group="density"]').check();assert.equal(await page.evaluate(()=>JSON.stringify(PARAMS)),base);
  const graph=page.locator('#easeGraph');await graph.scrollIntoViewIfNeeded();const rect=await graph.boundingBox();assert.ok(Math.abs(rect.height/rect.width-68/264)<.005);
  const styles=await page.evaluate(()=>{const g=document.getElementById('easeGraph'),t=document.querySelector('.recordTransport');return{dash:getComputedStyle(g.querySelector('.easeArms')).strokeDasharray,opacity:getComputedStyle(g.querySelector('.easeArms')).opacity,stroke:getComputedStyle(g.querySelector('.easeArms')).strokeWidth,transportBorder:getComputedStyle(t).borderTopWidth,controlInputBorder:getComputedStyle(document.getElementById('modPeriod')).borderTopWidth};});assert.equal(styles.dash,'3px, 3px');assert.equal(styles.opacity,'1');assert.equal(styles.stroke,'1px');assert.equal(styles.transportBorder,'0px');assert.equal(styles.controlInputBorder,'1px');
  const point=async(x,y)=>{await graph.scrollIntoViewIfNeeded();const r=await graph.boundingBox();return{x:r.x+(16+x*232)/264*r.width,y:r.y+(56-y*48)/68*r.height};};
  const click=async(x,y)=>{const p=await point(x,y);await page.mouse.click(p.x,p.y);};
  const drag=async(key,x,y,{shift=false,cancel=false}={})=>{const el=page.locator(`[data-curve-key="${key}"]`);await el.scrollIntoViewIfNeeded();const b=await el.boundingBox(),p=await point(x,y);if(shift)await page.keyboard.down('Shift');await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(p.x,p.y,{steps:5});if(cancel)await page.evaluate(()=>document.getElementById('easeGraph').dispatchEvent(new PointerEvent('pointercancel',{pointerId:1})));await page.mouse.up();if(shift)await page.keyboard.up('Shift');};
  const original=await page.evaluate(()=>_easeSnapshot());await click(.5,.5);assert.equal(await page.evaluate(()=>_easePoints.length),3);
  const split=await page.evaluate(()=>_easeSnapshot());assert.equal(await page.evaluate(()=>_easePast.length),1);
  await drag('1-point',.65,.7);const moved=await page.evaluate(()=>_easeSnapshot());assert.ok(Math.abs(moved[1].x-.65)<.01&&Math.abs(moved[1].y-.7)<.01);assert.equal(await page.evaluate(()=>_easePast.length),2);
  await page.keyboard.press('Control+z');assert.deepEqual(await page.evaluate(()=>_easeSnapshot()),split);await page.keyboard.press('Control+Shift+z');assert.deepEqual(await page.evaluate(()=>_easeSnapshot()),moved);
  await drag('1-point',.8,.2,{cancel:true});assert.deepEqual(await page.evaluate(()=>_easeSnapshot()),moved);
  await page.locator('[data-curve-key="1-point"]').focus();await page.keyboard.press('Enter');const corner=await page.evaluate(()=>_easeSnapshot());assert.deepEqual(corner[1].in,{x:corner[1].x,y:corner[1].y});assert.deepEqual(corner[1].out,corner[1].in);
  await drag('1-point',corner[1].x+.09,corner[1].y+.1,{shift:true});const restored=await page.evaluate(()=>_easeSnapshot());assert.equal(restored[1].x,corner[1].x);assert.ok(restored[1].out.x>restored[1].x&&restored[1].in.x<restored[1].x);
  await drag('1-out',restored[1].x,restored[1].y);assert.deepEqual(await page.evaluate(()=>_easePoints[1].out),{x:restored[1].x,y:restored[1].y});
  await page.locator('[data-curve-key="1-point"]').focus();await page.keyboard.press('Delete');assert.equal(await page.evaluate(()=>_easePoints.length),2);await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>_easePoints.length),3);
  await drag('0-point',.3,.4);assert.equal(await page.evaluate(()=>_easePoints[0].x),0);assert.equal(await page.evaluate(()=>_easePoints[0].y),0);
  // Active MOV owns even an empty undo stack. Other windows and native input do not.
  await page.evaluate(()=>{_easePast=[];_easeFuture=[];window.bondUndoCalls=0;_bondUndoApply=()=>{window.bondUndoCalls++;return true;};_viewFocused=true;});await graph.focus();await page.locator('#recordDialog').focus();await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>window.bondUndoCalls),0);
  const frozen=await page.evaluate(()=>_easeSnapshot());await page.evaluate(()=>{const other=document.createElement('div');other.className='mhDialog';other.id='otherTestPopup';other.tabIndex=0;document.body.append(other);other.focus();});await page.keyboard.press('Control+z');assert.deepEqual(await page.evaluate(()=>_easeSnapshot()),frozen);
  await page.evaluate(()=>{document.getElementById('otherTestPopup').remove();const t=document.createElement('textarea');t.id='nativeUndo';document.getElementById('recordDialog').append(t);t.focus();});await page.keyboard.type('abc');await page.keyboard.press('Control+z');assert.equal(await page.locator('#nativeUndo').inputValue(),'');assert.deepEqual(await page.evaluate(()=>_easeSnapshot()),frozen);await page.evaluate(()=>document.getElementById('nativeUndo').remove());
  await page.locator('#recordDialog').focus();await page.evaluate(()=>document.getElementById('recordDialog').dispatchEvent(new KeyboardEvent('keydown',{key:'z',code:'KeyZ',ctrlKey:true,isComposing:true,bubbles:true})));assert.deepEqual(await page.evaluate(()=>_easeSnapshot()),frozen);
  // Independent color ranges, piecewise playback, and original automatic color mode restoration.
  await page.locator('[data-record-group="bg"]').check();await page.locator('[data-record-group="fg"]').check();
  const colors=await page.evaluate(()=>{const before=[bgR,bgG,bgB,fgR,fgG,fgB,_fgAuto];Object.assign(_recordRanges.get('_bgR'),{from:10,to:90,count:2});Object.assign(_recordRanges.get('_fgG'),{from:50,to:150,count:2});_recordPeriod=1;_recordRepeats=1;_easePoints=MHCurve.insert(MHCurve.defaults(),.5,.8);_startModulation();_advanceModulation(0);_advanceModulation(250);const mid=[bgR,fgG];_advanceModulation(500);const end=[bgR,fgG];_stopModulation();return{before,mid,end,after:[bgR,bgG,bgB,fgR,fgG,fgB,_fgAuto]};});assert.ok(Math.abs(colors.mid[0]-74)<.001&&Math.abs(colors.mid[1]-130)<.001);assert.deepEqual(colors.end,[90,150]);assert.deepEqual(colors.before,colors.after);
  await page.locator('[data-record-group="bg"]').uncheck();await page.locator('[data-record-group="fg"]').uncheck();await page.locator('#recordDialog').screenshot({path:'test-results/mov-curve.png'});
  await page.locator('#modPeriod').focus();await page.keyboard.press('Escape');assert.equal(await page.locator('#recordDialog').count(),0);
  assert.deepEqual(errors,[]);assert.equal(original.length,2);console.log('PASS: MOV-only group selection, opaque 1px graph at half height, point insert/drag/cancel, tangent collapse/Shift restore, one undo per drag, active-popup/native/IME undo isolation, piecewise color playback and restore');
 }finally{await browser?.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
